using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HelpingHands.Models
{
    public class Card
    {
        public string CardNonce { get; set; }
        //
        // Summary:
        //     Address information for the card on file. Only the `postal_code` field is required
        //     for payments in the US and Canada. 
        public Address BillingAddress { get; set; }
        //
        // Summary:
        //     The full name printed on the credit card. 
        public string CardholderName { get; set; }
        //
        // Summary:
        //     An identifying token generated by `SqPaymentForm.verifyBuyer()`. Verification
        //     tokens encapsulate customer device information and 3-D Secure challenge results
        //     to indicate that Square has verified the buyer identity.
        public string VerificationToken { get; set; }
    }
}
